teradici/deploy

dev/domain-controller/README.md

Just an initial overview/plan for the restructuring of the readme file for Beta. **Not to be committed**.

stating potential re-structure of readme.md file

---

dev/domain-controller/README.md

Added the instructions provided by Bill and used in Flare for PowerShell deployment.

Microsoft PowerShell deployment

---

dev/domain-controller/README.md

Some initial changes I made on the doc from Mirela's comments. Meeting with her to discuss some of the other comments and suggested changes.

Initial changes based on Mirela comments 05/06

---

dev/domain-controller/README.md

Added the section on manually creating a service principal account.

Service Principal Pre-requisite

---

dev/domain-controller/README.md

A point on MSFT_xRemoteFile error

MSFT_xRemoteFile error details

---

dev/domain-controller/new-admin-vm/Install-CAM.ps1

Should check that deploymentId is set/valid before using it

* Fixed issue in case where deploymentId is null

---

dev/domain-controller/new-admin-vm/Install-CAM.ps1

TSW-66322 – added more informative error messages
TSW-66317 – fix test-script issues around finding files and folders
After we merge all of these I guess for now only Frank can create the .ps1.zip files?

TSW-66322 – added more informative error messages

---

dev/domain-controller/new-agent-vm/server2016-graphics-agent.json
dev/domain-controller/new-agent-vm/server2016-standard-agent.json

* made auto-enable shutdown a parameter
* enabled by default

Tsw 66537 enable auto shutoff

---

README.md

Changed README to point to correct template URL

TSW-66292 - change README to point to right URL

---

azuredeploy.json

Fix missing defaultValue null for tenantID in deployment template.

Fix missing default value for tenant

---

azuredeploy.json
end-user-application-machines/azuredeploy.parameters.json
frontend/new-admin-vm/Install-CAM.ps1

Change application VM size from D2_v3 to D2_v2

---

dev/domain-controller/new-admin-vm/Install-CAM.ps1

update Java to 1.8.0 build 144
update tomcat to 8.5.23

Tsw 64739 update vm au

---

frontend/new-admin-vm/sumo-admin-vm.json

The Sumo collector paths were incorrect for the Admin UI. Fixing.

Collect logs from Admin UI

---

end-user-application-machines/new-agent-vm/server2016-graphics-agent.json

* Downloading Nvidia Driver frm Teradici host Azue blob

Fixed issue downloading Nvidia Driver:

---

Deploy-CAM.ps1

@bill-dall 
With these changes i was able to run it like this without any prompts. 
```
.\Deploy-CAM.ps1 `
-domainAdminCredential $dnCred `
-domainName $domainName `
-registrationCode $secureRegistrationCode `
-spCredential $spCred `
-ResourceGroupName "Ivan-Cloud-Shell21411" `
-location 'eastus'
```

adding ResourceGroupname and Location as parameters for automation

---

Deploy-CAM.ps1

* AzureRm got updated for cloudshell and now SP password must be a securestring

Fixed cloudshell issue:

---

end-user-application-machines/new-agent-vm/Install-PCoIPAgent.ps1
frontend/new-admin-vm/Install-CAM-CS.ps1
frontend/new-cm-sg-ls-vm/azuredeploy.json
frontend/new-cm-sg-ls-vm/cm_setup_0.1.sh
frontend/new-cm-sg-ls-vm/user.properties

Update to use latest Sumo logic collector

Sumo logic

---

Deploy-CAM.ps1

Deploy a connection service in its own resource group.

---

Deploy-CAM.ps1

This should work for the 'SP deploying itself' issue. @cptera -note the strange extra filters I had to put on to see if it had rights already. Seems like a loose pattern match that they have by default...

Check if the SP needs a role assignment before attempting.

---

Deploy-CAM.ps1

Not sure if this catches every possible combinatin but according to  https://msdn.microsoft.com/en-us/library/ms853959.aspx only these are not valid \ / : * ? " < > |. We can expand on it further if we see something that is not handled

Better input validation

---

Deploy-CAM.ps1

since 3 didn't clear the error for me once today.

Increase number of retries

---

connection-service/azuredeploy.json
connection-service/new-cm-sg-ls-vm/azuredeploy.json
connection-service/new-cm-sg-ls-vm/azuredeploy.parameters.json
connection-service/new-sg-s/azuredeploy.parameters.json
connection-service/new-sg-s/new-sg-s.json

Rename cmNSG to sgNSG to make it more clear its associated with

---

README.md

Updated Readme Link:

---

Deploy-CAM.ps1

Improve error handling around authentication race conditions.
Improve version checking handling to handle SDK clean install case.
Three things that I ran into yesterday...

Remove unneeded parameters.

---

Deploy-CAM.ps1
azuredeploy.json
connection-service/azuredeploy.json
connection-service/azuredeploy.parameters.json
connection-service/new-app-gateway/azuredeploy.json
connection-service/new-cm-sg-ls-vm/azuredeploy.json
connection-service/new-cm-sg-ls-vm/cm_setup_0.1.sh
connection-service/new-cm-sg-ls-vm/sumo_cm_vm.json

Give the app gateway an internal IP in case external routing is not available (port 8443)
Rename some parameters for better clarity in the key vault
Make enableSecurityGateway switch for deployment of an overlay install or a connection service
Fix sumo paths in CM/SG machine

Internal external

---

Deploy-CAM.ps1

Any objection to use production environment?

Update to use production environment

---

connection-service/new-admin-vm/Install-ConnectionServer.ps1
remote-workstations/new-agent-vm/Install-PCoIPAgent.ps1

* Wait for service to be installed instead of waiting for registry key

Fixed Install Logic for Sumo-Logic:

---

Deploy-CAM.ps1
connection-service/new-admin-vm/Install-ConnectionServer.ps1
remote-workstations/new-agent-vm/Install-PCoIPAgent.ps1

* HttpUtility stopped working, found a fix

HTTP Utility doesn't work

---

Deploy-CAM.ps1

- Fixed domain name checking
- Add checking for banned username
- Fixed on not prompting username again if it is invalid password
- Add checking for password complexity

- Make warning more visible

---

Deploy-CAM.ps1
azuredeploy.json

* fixed issue where defaultIdleShutdownTime parameter wasn't passed to admin-rw machine

Fixed issue with admin-rw auto idle shutdown time:

---

Deploy-CAM.ps1

Remove confirmation on vnet access rights - but make a warning string.
Trim all appropriate input since... that's the right thing to do for UX.

Select vnets from a list, as well as subnets.

---

remote-workstations/new-agent-vm/server2016-graphics-agent.json
remote-workstations/new-agent-vm/server2016-standard-agent.json

* Updated to GRID 5.3 Driver (386.09)

Updated NVidia Windows Driver:

---

connection-service/new-app-gateway/azuredeploy.json

Looks like it sets it properly - now we just need to verify how impactful it is somehow...

Try to set app gateway timeout to 90 seconds

---

Deploy-CAM.ps1

* Internal Access with MFA is disabled

Disable MFA for internal:

---

connection-service/new-app-gateway/azuredeploy.json

* External Port should always be port 443

---

Deploy-CAM.ps1

Add 'list' permissions to SP so we can provide a nicer GUI later.

Keyvault list permissions

---

Deploy-CAM.ps1

* Change to subnet names instead of ids (doesn't work currently)

Fix automation switches:

---

connection-service/new-admin-vm/Install-ConnectionServer.ps1

* Switched from using .NET to openSSL windows binary to extract root certificate due to issues in some cases with .NET

Use openSSL for windows to get root cert:

---

connection-service/new-admin-vm/Install-ConnectionServer.ps1

* Try our initial .NET Cert Chain builder, if that fails try another .NET chain builder, if that fails use OpenSSL

Added Fallback methods for getting cert:

---

Deploy-CAM.ps1

Added a function to check for a resource that is available. Ported much of the code from the original Microsoft.Keyvault check.

TSW-71560: Added a check/register for Microsoft.Compute and Microsoft.Network

---

Deploy-CAM.ps1

* Doing a checks for Unix Modules and Windows Module versions/names

Microsoft broke things for us in cloudshell:

---

win10-templates/Win10Generic.json
win10-templates/Win10Generic.parameters.json

Point customers to win10 templates.

windows-10-templates-checkin

---

Deploy-CAM.ps1

Created Key Vault functions for Get and Set of secrets. Functions have retries and provide user readable error messages if the retries fail.

Tsw 74124 add logging and resilience around key vault operations

---

connection-service/new-cm-sg-ls-vm/azuredeploy.json

For some reason the old version isn't working, new one is

Test linuxcustomescript 2

---

Deploy-CAM.ps1

* Microsoft renamed Azure Powershell module (again)

Added version checks for Az module:

---

README.md

http://www.teradici.com/web-help/pcoip_cloud_access_manager/current/deploying_cloud_access_manager_with_Azure_cloud_shell/ -> http://www.teradici.com/web-help/pcoip_cloud_access_manager/current/

Updating README to change deploy web address

---

connection-service/new-vm-join-domain/new-vm-join-domain.json

* Try using older version of windows for conn-server

Lock Windows version for connection-server:

---

Deploy-CAM.ps1

They changed the name of the Module from Az.Profile to Az.Account

* New Az Module version 1.0.0 has different Module names

---

Deploy-CAM.ps1

* cloud shell modules' behavior has changed slightly

fixed Update-CAMUserCredential method for latest version of CloudShell

---

connection-service/new-admin-vm/Install-ConnectionServer.ps1

* DSC will loop through all available DCs for root cert and stop at the first successful one

Make ConnSrvr DSC more resilient:

---

Deploy-CAM.ps1

* Create a new role per subscription unless existing roll has wildcard scope or subscription is within scope already

Fixed issue with moving Subscriptions and roles:

---

AddManagedMachine.ps1

* This will make sure the SP creds for the selected connector can perform power opertations on the machine
* This will add the managed machine to CAM

Automate adding non-cam provisioned machines to CAM:

---

connection-service/new-cm-sg-ls-vm/cm_setup_0.1.sh
remote-workstations/new-agent-vm/Install-PCoIPAgent.ps1

* chnaged default TLS to 1.2 for Install Agent.ps1

* changed timeout to 55s

---

Deploy-CAM.ps1

* don't assume standard cam error response format

make error handling better:

---

Deploy-CAM.ps1

SP creds don't have permissions to query for Azure Object IDs so it must be provided explicitly by the user

Allow user to provide Azure Object ID

---

Deploy-CAM.ps1

* Update the self signed Gateway cert in the KeyVault on re-deploy

Update Gateway Certificate on Re-deploy:

---

Deploy-CAM.ps1

* Azure has deprecated SecureGateways and role no longer exists

SecureGateways deprecated:

---

connection-service/new-admin-vm/Install-ConnectionServer.ps1
remote-workstations/new-agent-vm/server2016-standard-agent.json

* Generate new self signed certs per connector
* Update default video driver

Generate new cert:

---

connection-service/new-vm-join-domain/new-vm-join-domain.json

Update connection server VM:

---

connection-service/new-vm-join-domain/new-vm-join-domain.json
connection-service/new-vm-join-domain/update-nic.json

Not working, but it works without it

Remove update NIC

---

connection-service/new-admin-vm/sumo.conf
connection-service/new-cm-sg-ls-vm/user.properties
remote-workstations/new-agent-vm/sumo.conf
remote-workstations/new-agent-vm/user.properties

Rotate Sumo Creds:

---

Deploy-CAM.ps1

* SecretValueText has been deprecated

Fix getting secrets from KeyVault:
